DataValuesJavascript.php
README.md
config.js
src/resources.php
src/values/UnDeserializableValue.js
tests/src/values/UnDeserializableValue.tests.js

- Common naming in `wikibase.serialization` was changed to `*Deserializer`.
- Applying the same parameter order as `dataValues.newDataValue`.

Updated UnDeserializableValue

---

DataValuesJavascript.php
lib/resources.php
src/resources.php
src/valueFormatters/resources.php
src/valueParsers/resources.php

The complexity of this regular expression is just not needed. Just search for the first occurrence of `/vendor/` or `/extensions/` and match everything from there, that's it. Using a regex character (`+`) as delimiter does have the advantage that it must not be repeated when calling `preg_quote`, it's always quoted.

Simplify remoteExtPath regex

---

DataValuesJavascript.php
README.md
composer.json

A thing called "Javascript" does not exist. This is the first of several small patches. This does not cause a breaking change, it's only fixing typos.

Fix typo in "JavaScript"

---

src/values/TimeValue.js

@snaterlicious, I suggest to simplify this structure a lot.
This is relevant in https://github.com/wmde/ValueView/pull/162. All `toLowerCase` calls can be removed there.

Simplify calendar model configuration structure

---

src/values/TimeValue.js

* No other precision is plural.
* Removed the `parseInt` because the variable is already int.
* Reversed the loop. The idea is that the precisions relevant in production are usually at the high end of the array.
Bug: [T89243](https://phabricator.wikimedia.org/T89243)

Fix inconsistency in MINUTES

---

README.md
src/values/TimeValue.js

As discussed in https://phabricator.wikimedia.org/T88438 and several other discussions.
Bug: [T89243](https://phabricator.wikimedia.org/T89243)

Avoid calling our timestamp strings ISO

---

DataValuesJavaScript.php
lib/resources.php

Explicitly depending on jquery.qunit breaks qunit-karma-based test running, since qunit-karma loads its own QUnit instance. This closes [T94394](https://phabricator.wikimedia.org/T94394).

Don't explicitly depend on jquery.qunit

---

.jshintrc
src/values/TimeValue.js
tests/src/values/TimeValue.tests.js

This restores the behavior of the old regex in https://github.com/wmde/DataValuesJavascript/blob/0.6.1/lib/time/time.Time.js#L259:
* The trailing "Z" is optional.
* Second is optional.
* Hour:minute is optional.
* Hour, minute and second can have any number of digits, similar to day and month.
Note that actual validation should *not* be done here but server-side instead. Therefor it's ok to have a very relaxed regex here.
Bug: [T89243](https://phabricator.wikimedia.org/T89243)

Optional hour:minute, second and timezone in TimeValue

---

src/values/UnDeserializableValue.js
tests/src/values/UnDeserializableValue.tests.js

made the error attribute of the value be a string, with
the error reason, for more consistency with the backend
implementation and for better ease of use.
also fixed more of the wording and variable names from
"ununserializable" to "undeserializable", for consistency purposes.
[Bug: T99231](https://phabricator.wikimedia.org/T99231)

Implement UnDeserializableValue::newFromJSON and toJSON

---

src/valueParsers/parsers/StringParser.js
tests/src/valueParsers/parsers/StringParser.tests.js

This patch changes the StringParser to return null when the given string
is empty.
Bug: T93572

Make StringParser parse empty string as null

---

src/values/TimeValue.js

Same patch in PHP: https://gerrit.wikimedia.org/r/#/c/194306/
[Bug: T99911](https://phabricator.wikimedia.org/T99911)

Unify names of time precision constants

---

DataValuesJavaScript.php

This is for consistency with all other places that do the same in our code base.

Use require instead of include

---

lib/globeCoordinate/globeCoordinate.GlobeCoordinate.js
tests/lib/globeCoordinate/globeCoordinate.GlobeCoordinate.tests.js

Prefer the injected value instead of the hard-coded 'http://www.wikidata.org/entity/Q2'.
Add tests.
Bug: [T105321](//phabricator.wikimedia.org/T105321)

GlobeCoordinate: support other globes

---

lib/globeCoordinate/globeCoordinate.GlobeCoordinate.js
tests/lib/globeCoordinate/globeCoordinate.GlobeCoordinate.tests.js

* Split big "Basic checks" test.
* Add test that `getDecimal` does **not** contain the globe.
* Avoid calling getters when not necessary.

Split very complex GlobeCoordinate test

---

lib/globeCoordinate/globeCoordinate.GlobeCoordinate.js
tests/lib/globeCoordinate/globeCoordinate.GlobeCoordinate.tests.js

Before #53 the implementation already supported both null and undefined precisions, but this was never tested properly, only slightly with a lazy `assert.equal( …, null )` that accepts `undefined` as `null`. #53 broke this feature, but not the test, because it was never calling `equals` with an undefined precision.
The backend also supports precision null, see https://github.com/DataValues/Geo/blob/master/src/Values/GlobeCoordinateValue.php.

Add support for precision null to GlobeCoordinate

---

lib/globeCoordinate/globeCoordinate.Formatter.js

* The main issue here is the missing `break`.
* 1 / 36000000 is not an option you can select in the UI, but is something that can be detected by the backend. At the moment this is shown as "special (±2.7777777777778e-8°)". With this addition this is shown as "special (1/10000')"
* The epsilon must be lowered together with the smallest predefined precision. I'm using the maximum number of zeros that a coordinate value of 360.000000000000… can have before IEEE makes it start becoming fuzzy (this is around 15 significant digits). Try `( 360.1 ).toFixed( 20 )` in the JavaScript console to see what I mean.

Add missing break to globeCoordinate.Formatter

---

src/values/MonolingualTextValue.js
src/values/NumberValue.js
tests/src/dataValues.DataValue.tests.js
tests/src/valueParsers/valueParsers.tests.js

Upper case means it must be an object, but these are not required to be objects.

Minor fixups to JSDoc comments

---

composer.json

This was introduced with 75343a823dc625bbc2966490b3d5001988837108 by @JeroenDeDauw. I tried to understand why, but can't figure it out. The component consists of nothing but a series of `…Installer` classes, including [a `MediaWikiInstaller` one](https://github.com/composer/installers/blob/master/src/Composer/Installers/MediaWikiInstaller.php). I can't find usages of these classes, neither today not back then when the dependency was introduced.
Either this was added by mistake, or (more likely) I'm missing something. @JeroenDeDauw, can you please have a look?

Remove composer/installers dependency

---

lib/globeCoordinate/globeCoordinate.GlobeCoordinate.js
src/values/GlobeCoordinateValue.js

This removes a bunch of obsolete comments and makes a method private that is not used anywhere outside of this class.

Make unused GlobeCoordinate.getDecimal private

---

src/values/TimeValue.js

`getYear`, `getMonth`, and so on are all unused. Instead I store the whole `timestamp` string now.
I keep the parsing and rebuilding that was done before in the `getTimestamp` method, even if I believe this is unused. This class is used to store values as they are coming from the backend. These values should always be in a strictly fixed format. But it's hard to prove this. At least the padding of the year must be flexible.
Note that `getSortKey` will be removed with #115. If this is done this code can be simplified even further, I believe, to the point where we just get rid of the `pad` function.

Remove unused getters from TimeValue

---

DataValuesJavaScript.php
README.md
src/values/TimeValue.js

I removed this in #116, but I was wrong about the usage. This method is still used in a single place in the ValueView component on a line that was previously not type hinted at all: https://phabricator.wikimedia.org/diffusion/GDVV/browse/master/src/ExpertExtender/ExpertExtender.CalendarHint.js;6c328d1a0e5014313c2b11b1691b75e0a2d1b5c2$98
My goal still is to remove said code in the ValueView component, but for the moment it's easier to temporarily restore the method here.

Restore TimeValue.getYear still used by ValueView

---

README.md
src/values/TimeValue.js

This reverts #118 now that the last usage is gone via https://gerrit.wikimedia.org/r/370835.
[Bug: T172916](https://phabricator.wikimedia.org/T172916)

Remove now unused TimeValue.getYear

---

src/DataValue.js
src/valueFormatters/formatters/ValueFormatter.js
src/valueParsers/ValueParserStore.js
src/valueParsers/parsers/ValueParser.js

This does make the documentation much stronger. Without this, an IDE has a hard time figuring out that the `$.extends` stuff belongs to the class constructor directly above. With this, my IDE finally understands which properties and methods belong to these classes.
If you merge this, please also merge https://github.com/wmde/WikibaseDataModelJavaScript/pull/75.

Add missing class level documentation links

---

src/valueFormatters/formatters/ValueFormatter.js

[Bug: T172916](https://phabricator.wikimedia.org/T172916)

Simplify ValueFormatter interface, remove ValueFormatterStore

---

README.md
tests/lib/globeCoordinate/globeCoordinate.GlobeCoordinate.tests.js
tests/src/valueParsers/ValueParserStore.tests.js
tests/src/values/TimeValue.tests.js

* I think it would be cool to have the minus 16,000 lines change #124 in this release. But I just talked to @manicki and he thinks this change can wait. Would be cool for a future 1.0 release.
* I would **love** to have #122 as well as #123 in this release. Both go together and can be considered a single ticket.

Release 0.9.0

---

lib/globeCoordinate/globeCoordinate.GlobeCoordinate.js

~~Together with #115~~ this will allow us to remove an other giant chunk of the formatting logic.
Note that I intentionally changed this code in a way that no test needed adjustment. (And there are quite a lot of test cases.) The `/ 2` division makes sense when you think of it this way: Let's say the first coordinate is given as 173°, and the second as 173.5°, both with a precision of 1°. This means the first is rendered as "173°", but the second as "174°". Because of this they must be considered unequal, even if the difference between the two is only 1/2 of the precision.
[Bug: T172916](https://phabricator.wikimedia.org/T172916)

Rewrite globeCoordinate.GlobeCoordinate.equals

---

README.md
package.json

Looks like I messed up and cannot reopen https://github.com/wmde/DataValuesJavaScript/pull/127, then submitting again.
This should not be merged before https://github.com/wmde/DataValuesJavaScript/pull/128 was, otherwise release notes are a lie.

Release 0.10.0

---

lib/util/util.inherit.js
src/valueParsers/parsers/StringParser.js
src/values/MonolingualTextValue.js
src/values/MultilingualTextValue.js
src/values/NumberValue.js
src/values/UnDeserializableValue.js
tests/src/valueParsers/parsers/FloatParser.tests.js
tests/src/valueParsers/parsers/StringParser.tests.js
tests/src/valueParsers/valueParsers.tests.js
tests/src/values/NumberValue.tests.js
tests/src/values/TimeValue.tests.js
tests/src/values/UnDeserializableValue.tests.js

I contacted Daniel Werner and asked him which email address he prefers.
I had two reasons to touch this:
* Daniels wikimedia.de email does not exist any more.
* He used so many different @author tags and I wanted to unify them.

Use Daniel Werners preferred email address

---

README.md
lib/globeCoordinate/globeCoordinate.GlobeCoordinate.js
src/values/QuantityValue.js
tests/lib/globeCoordinate/globeCoordinate.GlobeCoordinate.tests.js

- GlobeCoordinate. getDecimal has not been used since a50a48e5cedcb5
- QuantityValue.get(UpperBound|LowerBound|Amount) has not been used
since fadb3ab8b5c

Remove several methods

---

.gitignore
.travis.yml
README.md
package-lock.json
package.json

The lockfile is needed for npm audit to analyze the packages that will
be installed.
The major version upgrade to eslint was done to resolve a warning in the
latest Dependabot mail.

chore: upgrade dependencies and add lockfile
